server:
  port: 8000
spring:
  application:
    name: student-service
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanager?serverTimezone=Asia/Jakarta
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
product:
  jms:
    destination: product